In [1]:
" 1. What is a Python library? Why do we use Python libraries?"

' 1. What is a Python library? Why do we use Python libraries?'

In [2]:
# Python library is a collection of function.
# Python libraries serve several purposes:
# 1. Code Reusability:
# 2. optimized
# 3. Efficiency:
# 4. Rapid Development
#Python libraries are essential tools that empower developers by offering pre-built functionalities,
# promoting code reuse, and fostering a collaborative environment within the Python community.

In [3]:
" 2. What is the difference between Numpy array and List?"

' 2. What is the difference between Numpy array and List?'

In [4]:
# In a Python list, you can have elements of different data types. For example, a list can contain integers, strings, and other objects in any combination.
# NumPy arrays, on the other hand, are homogeneous, meaning all elements must be of the same data type.
# This homogeneity allows for more efficient storage and operations on the data.

In [5]:
"""
 3. Find the shape, size and dimension of the following array?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
 """

'\n 3. Find the shape, size and dimension of the following array?\n [[1, 2, 3, 4]\n [5, 6, 7, 8],\n [9, 10, 11, 12]]\n '

In [9]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_shape=arr.shape
arr_size=arr.size
arr_dim=arr.ndim
print("Array_shape", arr_shape)
print("Array size", arr_size)
print("Array dimension", arr_dim)

Array_shape (3, 4)
Array size 12
Array dimension 2


In [10]:
"""
 4. Write python code to access the first row of the following array?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
 """

'\n 4. Write python code to access the first row of the following array?\n [[1, 2, 3, 4]\n [5, 6, 7, 8],\n [9, 10, 11, 12]]\n '

In [15]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
first_row=arr1[0]
print("The first row of given array are:-", first_row)

The first row of given array are:- [1 2 3 4]


In [14]:
"""
5. How do you access the element at the third row and fourth column from the given numpy array?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
 """

'\n5. How do you access the element at the third row and fourth column from the given numpy array?\n [[1, 2, 3, 4]\n [5, 6, 7, 8],\n [9, 10, 11, 12]]\n '

In [20]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
element=arr2[2,3]
print("element at the 3rd row and 4th coloum: ", element)

element at the 3rd row and 4th coloum:  12


In [21]:
""" 6. Write code to extract all odd-indexed elements from the given numpy array?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]"""

' 6. Write code to extract all odd-indexed elements from the given numpy array?\n [[1, 2, 3, 4]\n [5, 6, 7, 8],\n [9, 10, 11, 12]]'

In [23]:
arr3=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
odd_index_element=arr3[:,[1,3]].flatten()
print("all odd-indexed elements are ", odd_index_element)

all odd-indexed elements are  [ 2  4  6  8 10 12]


In [24]:
"7. How can you generate a random 3x3 matrix with values between 0 and 1?"

'7. How can you generate a random 3x3 matrix with values between 0 and 1?'

In [42]:
arr4=np.random.rand(3,3)
arr4

array([[0.54373073, 0.15953218, 0.89463257],
       [0.21526571, 0.93513972, 0.28635963],
       [0.35010428, 0.56517084, 0.53451251]])

In [36]:
" 8. Describe the difference between np.random.rand and np.random.randn?"

' 8. Describe the difference between np.random.rand and np.random.randn?'

In [39]:
#np.random.rand generates random numbers from a uniform distribution between 0 and 1,
#while np.random.randn generates random numbers from a standard normal distribution with a mean of 0 and a standard deviation of 1.

In [43]:
""" 9. Write code to increase the dimension of the following array?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]"""

' 9. Write code to increase the dimension of the following array?\n [[1, 2, 3, 4]\n [5, 6, 7, 8],\n [9, 10, 11, 12]]'

In [50]:
arr4=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
arr4_expand=np.expand_dims(arr4,axis=0)
arr4_expand.ndim

3

In [53]:
"""
 10. How to transpose the following array in NumPy?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]"""

'\n 10. How to transpose the following array in NumPy?\n [[1, 2, 3, 4]\n [5, 6, 7, 8],\n [9, 10, 11, 12]]'

In [56]:
orignal_arr=np.array([[1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12]])
transpose_arr=orignal_arr.transpose()
print("orignal array :-")
print(orignal_arr)
print("transepose array:-")
print(transpose_arr)

orignal array :-
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
transepose array:-
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [58]:
"""
 11. Consider the following matrix:
 Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
 Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
  Perform the following operation using Python
 1.Index wise multiplicatio
 2.Matrix multiplicatio
 3.Add both the matric
 4.Subtract matrix B from
 5.Divide Matrix B by A
 """

'\n 11. Consider the following matrix:\n Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]\n Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]\n  Perform the following operation using Python\n 1.Index wise multiplicatio\n 2.Matrix multiplicatio\n 3.Add both the matric\n 4.Subtract matrix B from \n 5.Divide Matrix B by A\n '

In [61]:
matrix_A=np.array([[1,2,3,4],
                   [5,6,7,8],
                  [9,10,11,12]])
matrix_B=np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])
index_wise_multiplication=matrix_A*matrix_B
matrix_multiplication=np.dot(matrix_A ,matrix_B.T)
add_matrix=matrix_A+matrix_B
subtract_matrix=matrix_A - matrix_B
divide_matrix= np.divide(matrix_B, matrix_A)
print("index wise multiplication:")
print(index_wise_multiplication)
print("matrix_multiplication:")
print(matrix_multiplication)
print("addition of matrix are:")
print(add_matrix)
print("subtraction of matrix")
print(subtract_matrix)
print("divide matric B by A are:")
print(divide_matrix)

index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
matrix_multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
addition of matrix are:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
subtraction of matrix
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
divide matric B by A are:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [62]:
" 12.  Which function in Numpy can be used to swap the byte order of an array?"

' 12.  Which function in Numpy can be used to swap the byte order of an array?'

In [64]:
# byteswap function is used to swap the byte order of an array
arr5=np.array([1,2,3,4,5])
swapped_array=arr5.byteswap()
swapped_array

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744, 360287970189639680])

In [65]:
"13.  What is the significance of the np.linalg.inv function?"

'13.  What is the significance of the np.linalg.inv function?'

In [66]:
# The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix.
A=np.array([[1,2],
            [3,4]])
inverse_A=np.linalg.inv(A)
inverse_A

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [67]:
"14. What does the np.reshape function do, and how is it used?"

'14. What does the np.reshape function do, and how is it used?'

In [71]:
# The np.reshape function in NumPy is used to change the shape (dimensions) of an array without changing its data.
# but condition is matrix_A(row*coloum)==total no of element in matrix_A
arr6=np.random.randint(1,5, size=(3,4))
matrix_A=arr6
matrix_reshape=matrix_A.reshape(6,2)
print("Orignal_matrix_A")
print(matrix_A)
print("After reshaping a matrix :")
print(matrix_reshape)

Orignal_matrix_A
[[1 4 2 1]
 [4 4 1 1]
 [4 1 1 1]]
After reshaping a matrix :
[[1 4]
 [2 1]
 [4 4]
 [1 1]
 [4 1]
 [1 1]]


In [72]:
" 15. What is broadcasting in Numpy?"

' 15. What is broadcasting in Numpy?'

In [73]:
# Broadcasting is a powerful mechanism in NumPy that allows us to perform operations on arrays of different shapes.
# This can be very useful for simplifying code and making it more efficient.